import { useMemo, useState } from 'react';

export type StaffMember = { id: string; name: string; email: string; role: string; status: 'pending' | 'authorized' };
type Patient = { id: string; name: string; age: string; disease: string; address: string; email: string; contact: string; emergencyName: string; emergencyContact: string; payment: string; paymentStatus: 'Paid' | 'Pending'; transaction: string; report: string };

const seedPatients: Patient[] = [
  { id: 'PT-2048', name: 'Maya Patel', age: '42', disease: 'Migraine', address: '12 Lake View Road, Bengaluru', email: 'maya@email.com', contact: '+91 98765 44321', emergencyName: 'Ravi Patel', emergencyContact: '+91 98765 44322', payment: 'Card', paymentStatus: 'Paid', transaction: 'TXN-784512', report: 'CBC results.pdf' },
  { id: 'PT-2047', name: 'Arjun Mehta', age: '31', disease: 'Hypertension', address: '45 Green Park, New Delhi', email: 'arjun@email.com', contact: '+91 98110 82371', emergencyName: 'Nisha Mehta', emergencyContact: '+91 98110 82372', payment: 'UPI', paymentStatus: 'Pending', transaction: 'TXN-784496', report: '' },
];
const blank = (): Omit<Patient, 'id'> => ({ name: '', age: '', disease: '', address: '', email: '', contact: '', emergencyName: '', emergencyContact: '', payment: 'Card', paymentStatus: 'Pending', transaction: '', report: '' });

export default function Dashboard({ mode, staff, onAuthorize, onLogout }: { mode: 'staff' | 'admin'; staff: StaffMember[]; onAuthorize: (id: string) => void; onLogout: () => void }) {
  const [page, setPage] = useState<'home' | 'new' | 'search' | 'details'>('home');
  const [patients, setPatients] = useState(seedPatients);
  const [form, setForm] = useState(blank());
  const [query, setQuery] = useState('');
  const [notice, setNotice] = useState('');
  const [selected, setSelected] = useState<Patient | null>(null);
  const results = useMemo(() => patients.filter(p => `${p.name} ${p.id} ${p.contact}`.toLowerCase().includes(query.toLowerCase())), [patients, query]);
  const save = (e: React.FormEvent) => { e.preventDefault(); if (Object.entries(form).some(([key, value]) => key !== 'report' && !value)) return setNotice('Complete all required fields before creating this record.'); const patient = { ...form, id: `PT-${2050 + patients.length}` }; setPatients([patient, ...patients]); setForm(blank()); setNotice(`${patient.name} was added successfully.`); };
  const admin = mode === 'admin';
  return <div className="app-shell">
    <header className="topbar"><div className="logo">✦ <span>NEURO</span><b>CYTE</b></div><div><span className="secure">● Secure session</span><button className="signout" onClick={onLogout}>Sign out ↗</button></div></header>
    <div className="workspace"><aside><div className="profile"><i>{admin ? 'AD' : 'JR'}</i><div><strong>{admin ? 'Administrator' : 'Jordan Reyes'}</strong><small>{admin ? 'Staff administration' : 'Patient services'}</small></div></div><p className="nav-label">{admin ? 'Administration' : 'Patient management'}</p>{admin ? <Nav active label="Staff authorization" icon="✓" /> : <><Nav label="Dashboard" icon="⌘" active={page === 'home'} onClick={() => setPage('home')} /><Nav label="New patient" icon="+" active={page === 'new'} onClick={() => { setPage('new'); setNotice(''); }} /><Nav label="Find patient" icon="⌕" active={page === 'search'} onClick={() => setPage('search')} /></>}<small className="network">● Clinical network online</small></aside>
    <main>{admin ? <Admin staff={staff} onAuthorize={onAuthorize} /> : page === 'new' ? <NewPatient form={form} setForm={setForm} notice={notice} save={save} /> : page === 'search' ? <Search query={query} setQuery={setQuery} patients={results} onSelect={patient => { setSelected(patient); setPage('details'); }} /> : page === 'details' && selected ? <PatientDetails patient={selected} onBack={() => setPage('search')} onUpdate={updated => { setPatients(current => current.map(patient => patient.id === updated.id ? updated : patient)); setSelected(updated); }} /> : <Home patients={patients} go={setPage} />}</main></div>
  </div>;
}

function Home({ patients, go }: { patients: Patient[]; go: (p: 'new' | 'search') => void }) { return <><Heading eyebrow="Patient services" title="Good morning, Jordan" text="Manage patient records and intake from one secure workspace." /><div className="cards"><button onClick={() => go('new')}><em>+</em><div><strong>Register new patient</strong><span>Create a complete patient record and payment entry.</span></div>→</button><button onClick={() => go('search')}><em>⌕</em><div><strong>Find existing patient</strong><span>Search by name, patient ID, or phone number.</span></div>→</button></div><div className="section-title"><div><h2>Recently added patients</h2><p>Latest records in your care team.</p></div><button onClick={() => go('search')}>View all records →</button></div><Patients patients={patients.slice(0, 3)} /></> }
function NewPatient({ form, setForm, notice, save }: { form: Omit<Patient,'id'>; setForm: React.Dispatch<React.SetStateAction<Omit<Patient,'id'>>>; notice: string; save: (e: React.FormEvent) => void }) { const input = (key: keyof Omit<Patient,'id'>, label: string, optional = false, type = 'text') => <label><span>{label}{!optional && <b> *</b>}</span><input required={!optional} type={type} value={form[key]} onChange={e => setForm({ ...form, [key]: e.target.value })} /></label>; return <><Heading eyebrow="Patient intake" title="Register new patient" text="Fields marked with * are required to create a patient record." /><form className="patient-form" onSubmit={save}><Block n="01" title="Personal details"><div className="grid">{input('name','Full name')}{input('age','Age',false,'number')}{input('disease','Disease / condition')}{input('contact','Contact number')}{input('email','Email address',false,'email')}<label className="wide"><span>Residential address <b>*</b></span><input required value={form.address} onChange={e => setForm({...form,address:e.target.value})}/></label></div></Block><Block n="02" title="Emergency contact"><div className="grid">{input('emergencyName','Contact name')}{input('emergencyContact','Contact number')}</div></Block><Block n="03" title="Payment transaction"><div className="grid"><label><span>Payment method <b>*</b></span><select value={form.payment} onChange={e=>setForm({...form,payment:e.target.value})}><option>Card</option><option>Cash</option><option>UPI</option><option>Insurance</option></select></label><label><span>Payment status <b>*</b></span><select value={form.paymentStatus} onChange={e=>setForm({...form,paymentStatus:e.target.value as Patient['paymentStatus']})}><option>Pending</option><option>Paid</option></select></label>{input('transaction','Transaction / receipt ID')}</div></Block><Block n="04" title="Clinical reports" optional><label className="upload"><input type="file" onChange={e=>setForm({...form,report:e.target.files?.[0]?.name || ''})}/><strong>{form.report || '↑  Attach reports if available'}</strong><small>Optional — doctors can add or update reports later.</small></label></Block>{notice && <p className={notice.includes('success') ? 'ok' : 'warning'}>{notice}</p>}<footer><span>* Required information</span><button>Create patient record →</button></footer></form></> }
function Search({ query, setQuery, patients, onSelect }: { query: string; setQuery: (x:string)=>void; patients: Patient[]; onSelect:(patient:Patient)=>void }) { return <><Heading eyebrow="Patient records" title="Find existing patient" text="Select a patient to view their record, payment status, and reports." /><div className="search"><span>⌕</span><input autoFocus value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search patients..." /></div><p className="results">{patients.length} records found</p><Patients patients={patients} onSelect={onSelect}/></> }
function Admin({ staff, onAuthorize }: {staff:StaffMember[];onAuthorize:(id:string)=>void}) { const pending = staff.filter(x=>x.status==='pending'); return <><Heading eyebrow="Administrator workspace" title="Staff authorization" text="Review and authorize employees before they can access patient services." /><div className="admin-note">◆ Only authorized staff may sign in. Approving an account grants access to the staff dashboard.</div><div className="section-title"><div><h2>Registration requests</h2><p>New employees awaiting your approval.</p></div><strong>{pending.length} pending</strong></div><div className="staff-list">{pending.map(person=><div className="staff" key={person.id}><i>{person.name.split(' ').map(n=>n[0]).join('')}</i><div><strong>{person.name}</strong><span>{person.email}</span></div><small>{person.role}</small><button onClick={()=>onAuthorize(person.id)}>Authorize access</button></div>)}{!pending.length&&<div className="empty">All staff registrations have been reviewed.</div>}</div></> }
function PatientDetails({ patient, onBack, onUpdate }: { patient: Patient; onBack:()=>void; onUpdate:(patient:Patient)=>void }) { const [message, setMessage] = useState(''); return <><button className="back" onClick={onBack}>← Back to patient search</button><div className="detail-hero"><div className="detail-avatar">{patient.name.split(' ').map(n=>n[0]).join('')}</div><div><p>Patient record · {patient.id}</p><h1>{patient.name}</h1><span>{patient.age} years · {patient.disease}</span></div><div className={`payment-badge ${patient.paymentStatus.toLowerCase()}`}>● Payment {patient.paymentStatus}</div></div><div className="detail-grid"><section className="detail-card"><h2>Personal details</h2><Data label="Email" value={patient.email}/><Data label="Contact number" value={patient.contact}/><Data label="Address" value={patient.address}/><Data label="Disease / condition" value={patient.disease}/></section><section className="detail-card"><h2>Emergency contact</h2><Data label="Name" value={patient.emergencyName}/><Data label="Contact number" value={patient.emergencyContact}/><h2 className="payment-title">Payment details</h2><Data label="Method" value={patient.payment}/><Data label="Transaction ID" value={patient.transaction}/><label className="status-control">Payment status<select value={patient.paymentStatus} onChange={e=>onUpdate({...patient,paymentStatus:e.target.value as Patient['paymentStatus']})}><option>Pending</option><option>Paid</option></select></label></section><section className="detail-card report-card"><h2>Clinical reports</h2><p>Reports can be added and updated by doctors.</p>{patient.report ? <div className="report-file">▣ {patient.report}</div> : <div className="no-report">No report attached yet.</div>}<label className="upload report-upload"><input type="file" onChange={e=>{const report=e.target.files?.[0]?.name;if(report){onUpdate({...patient,report});setMessage('Report uploaded successfully.')}}}/><strong>↑ Upload or replace report</strong><small>PDF, image, or clinical document</small></label>{message&&<p className="ok">{message}</p>}</section></div></> }
function Heading({eyebrow,title,text}:{eyebrow:string;title:string;text:string}) { return <div className="heading"><p>{eyebrow}</p><h1>{title}</h1><span>{text}</span></div> }
function Block({n,title,optional,children}:{n:string;title:string;optional?:boolean;children:React.ReactNode}) { return <section><h2><i>{n}</i>{title}{optional&&<small>Optional</small>}</h2>{children}</section> }
function Data({label,value}:{label:string;value:string}) { return <div className="data"><span>{label}</span><strong>{value}</strong></div> }
function Patients({patients,onSelect}:{patients:Patient[];onSelect?:(patient:Patient)=>void}) { return <div className="patients">{patients.map(p=><button className="patient" key={p.id} onClick={()=>onSelect?.(p)}><i>{p.name.split(' ').map(n=>n[0]).join('')}</i><div><strong>{p.name}</strong><span>{p.id} · {p.age} years · {p.disease}</span></div><small>{p.contact}</small><em className={p.paymentStatus.toLowerCase()}>{p.paymentStatus}</em></button>)}{!patients.length&&<div className="empty">No patient records match that search.</div>}</div> }
function Nav({label,icon,active,onClick}:{label:string;icon:string;active?:boolean;onClick?:()=>void}) { return <button onClick={onClick} className={active?'active':''}><i>{icon}</i>{label}</button> }
