import { useState } from 'react';

export default function LoginModal({ onClose, staff, onStaffLogin, onAdminLogin, onRegister }) {
  const [tab,setTab]=useState('login'); const [email,setEmail]=useState(''); const [password,setPassword]=useState(''); const [name,setName]=useState(''); const [role,setRole]=useState(''); const [message,setMessage]=useState('');
  const login=(e)=>{e.preventDefault(); if(!email||!password)return setMessage('Enter your work email and password.'); const record=staff.find(x=>x.email.toLowerCase()===email.toLowerCase()); if(record?.status==='pending')return setMessage('Your registration is awaiting administrator authorization.'); onStaffLogin();};
  const register=(e)=>{e.preventDefault();if(!name||!email||!role||!password)return setMessage('Please complete all registration fields.');if(staff.some(x=>x.email===email))return setMessage('A request already exists for this email.');onRegister({id:String(Date.now()),name,email,role,status:'pending'});setMessage('Registration received. An administrator must authorize your account before you can sign in.');};
  return <div className="modal-bg" onClick={e=>e.target===e.currentTarget&&onClose()}><div className="auth-modal"><header><div><b>✦ NEUROCYTE</b><small>Secure clinical operations portal</small></div><button onClick={onClose}>×</button></header><nav><button className={tab==='login'?'selected':''} onClick={()=>{setTab('login');setMessage('')}}>Staff login</button><button className={tab==='register'?'selected':''} onClick={()=>{setTab('register');setMessage('')}}>Register</button><button className={tab==='admin'?'selected':''} onClick={()=>{setTab('admin');setMessage('')}}>Admin login</button></nav><div className="auth-content">{tab==='login'&&<form onSubmit={login}><h2>Welcome back</h2><p>Sign in with an authorized staff account.</p><Input label="Work email" value={email} set={setEmail} type="email"/><Input label="Password" value={password} set={setPassword} type="password"/>{message&&<Message text={message}/>}<button>Sign in →</button><small className="switch">New employee? <a onClick={()=>setTab('register')}>Register for access</a></small></form>}{tab==='register'&&<form onSubmit={register}><h2>Staff registration</h2><p>Your request will need approval before sign-in is enabled.</p><Input label="Full name" value={name} set={setName}/><Input label="Work email" value={email} set={setEmail} type="email"/><Input label="Job role" value={role} set={setRole}/><Input label="Create password" value={password} set={setPassword} type="password"/>{message&&<Message text={message}/>}<button>Request access →</button></form>}{tab==='admin'&&<form onSubmit={e=>{e.preventDefault();onAdminLogin()}}><i className="admin-chip">◆ Administrative access</i><h2>Administrator sign in</h2><p>Authorize incoming staff registration requests.</p><Input label="Admin username" value={email} set={setEmail}/><Input label="Password" value={password} set={setPassword} type="password"/><button className="admin-button">Enter admin workspace →</button></form>}</div></div></div>;
}
function Input({label,value,set,type='text'}) { return <label className="auth-input"><span>{label}</span><input type={type} value={value} onChange={e=>set(e.target.value)} required /></label> }
function Message({text}) { return <div className="auth-message">{text}</div> }
